set(_CATKIN_CURRENT_PACKAGE "autonomy_navigation")
set(autonomy_navigation_VERSION "0.1.0")
set(autonomy_navigation_MAINTAINER "Navigation Team <navigation-team@example.com>")
set(autonomy_navigation_PACKAGE_FORMAT "2")
set(autonomy_navigation_BUILD_DEPENDS "geometry_msgs" "message_generation" "nav_msgs" "rospy" "sensor_msgs" "std_msgs" "tf")
set(autonomy_navigation_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "rospy" "sensor_msgs" "std_msgs" "tf")
set(autonomy_navigation_BUILDTOOL_DEPENDS "catkin")
set(autonomy_navigation_BUILDTOOL_EXPORT_DEPENDS )
set(autonomy_navigation_EXEC_DEPENDS "geometry_msgs" "message_runtime" "nav_msgs" "rospy" "sensor_msgs" "std_msgs" "tf")
set(autonomy_navigation_RUN_DEPENDS "geometry_msgs" "message_runtime" "nav_msgs" "rospy" "sensor_msgs" "std_msgs" "tf")
set(autonomy_navigation_TEST_DEPENDS )
set(autonomy_navigation_DOC_DEPENDS )
set(autonomy_navigation_URL_WEBSITE "")
set(autonomy_navigation_URL_BUGTRACKER "")
set(autonomy_navigation_URL_REPOSITORY "")
set(autonomy_navigation_DEPRECATED "")