# CMake generated Testfile for 
# Source directory: /home/ruilinli/SimEnv/src
# Build directory: /home/ruilinli/SimEnv/build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("gtest")
subdirs("building_generator_core")
subdirs("hector_slam/hector_geotiff_launch")
subdirs("hector_slam/hector_slam")
subdirs("hector_slam/hector_slam_launch")
subdirs("building_generator_interfaces")
subdirs("hector_slam/hector_map_tools")
subdirs("hector_slam/hector_nav_msgs")
subdirs("uav_simulator/Utils/quadrotor_msgs")
subdirs("unitree_guide/unitree_ros_to_real/unitree_legged_sdk")
subdirs("unitree_guide/unitree_ros/robots/a1_description")
subdirs("uav_simulator/Utils/cmake_utils")
subdirs("hector_slam/hector_geotiff")
subdirs("hector_slam/hector_geotiff_plugins")
subdirs("hector_slam/hector_marker_drawing")
subdirs("uav_simulator/map_generator")
subdirs("uav_simulator/Utils/pose_utils")
subdirs("building_obstacles")
subdirs("hector_slam/hector_compressed_map_transport")
subdirs("building_generator_classic")
subdirs("hector_slam/hector_imu_attitude_to_tf")
subdirs("hector_slam/hector_imu_tools")
subdirs("hector_slam/hector_map_server")
subdirs("hector_slam/hector_trajectory_server")
subdirs("Mid360_imu_sim")
subdirs("uav_simulator/Utils/odom_visualization")
subdirs("livox_ros_driver/livox_ros_driver")
subdirs("uav_simulator/local_sensing")
subdirs("uav_simulator/mockamap")
subdirs("uav_simulator/so3_control")
subdirs("hector_slam/hector_mapping")
subdirs("uav_simulator/Utils/multi_map_server")
subdirs("uav_simulator/Utils/uav_utils")
subdirs("uav_simulator/so3_quadrotor_simulator")
subdirs("unitree_guide/unitree_ros_to_real/unitree_legged_msgs")
subdirs("unitree_guide/unitree_ros/unitree_legged_control")
subdirs("unitree_guide/unitree_ros_to_real/unitree_legged_real")
subdirs("unitree_guide/unitree_guide/unitree_actuator_sdk/unitree_motor_ctrl")
subdirs("uav_simulator/Utils/rviz_plugins")
subdirs("unitree_guide/unitree_ros/unitree_controller")
subdirs("unitree_guide/unitree_ros/unitree_gazebo")
subdirs("unitree_guide/unitree_guide/unitree_guide")
subdirs("fast_lio")
subdirs("unitree_guide/unitree_guide/unitree_move_base")
subdirs("uav_simulator/Utils/waypoint_generator")
