// Generated by gencpp from file autonomy_navigation/DangerCandidate.msg
// DO NOT EDIT!


#ifndef AUTONOMY_NAVIGATION_MESSAGE_DANGERCANDIDATE_H
#define AUTONOMY_NAVIGATION_MESSAGE_DANGERCANDIDATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace autonomy_navigation
{
template <class ContainerAllocator>
struct DangerCandidate_
{
  typedef DangerCandidate_<ContainerAllocator> Type;

  DangerCandidate_()
    : header()
    , position()
    , confidence(0.0)
    , target_type()  {
    }
  DangerCandidate_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , confidence(0.0)
    , target_type(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_type_type;
  _target_type_type target_type;





  typedef boost::shared_ptr< ::autonomy_navigation::DangerCandidate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autonomy_navigation::DangerCandidate_<ContainerAllocator> const> ConstPtr;

}; // struct DangerCandidate_

typedef ::autonomy_navigation::DangerCandidate_<std::allocator<void> > DangerCandidate;

typedef boost::shared_ptr< ::autonomy_navigation::DangerCandidate > DangerCandidatePtr;
typedef boost::shared_ptr< ::autonomy_navigation::DangerCandidate const> DangerCandidateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autonomy_navigation::DangerCandidate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autonomy_navigation::DangerCandidate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autonomy_navigation::DangerCandidate_<ContainerAllocator1> & lhs, const ::autonomy_navigation::DangerCandidate_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.confidence == rhs.confidence &&
    lhs.target_type == rhs.target_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autonomy_navigation::DangerCandidate_<ContainerAllocator1> & lhs, const ::autonomy_navigation::DangerCandidate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autonomy_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autonomy_navigation::DangerCandidate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autonomy_navigation::DangerCandidate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autonomy_navigation::DangerCandidate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autonomy_navigation::DangerCandidate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autonomy_navigation::DangerCandidate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autonomy_navigation::DangerCandidate_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autonomy_navigation::DangerCandidate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e795b58e8a82e9507d183a0de0aa73a";
  }

  static const char* value(const ::autonomy_navigation::DangerCandidate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e795b58e8a82e95ULL;
  static const uint64_t static_value2 = 0x07d183a0de0aa73aULL;
};

template<class ContainerAllocator>
struct DataType< ::autonomy_navigation::DangerCandidate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autonomy_navigation/DangerCandidate";
  }

  static const char* value(const ::autonomy_navigation::DangerCandidate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autonomy_navigation::DangerCandidate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A candidate emitted by the perception component.\n"
"# header.frame_id must identify the coordinate system of position, normally\n"
"# \"real_sense\" or \"base\". position is expressed in that frame.\n"
"\n"
"std_msgs/Header header\n"
"geometry_msgs/Point position\n"
"float32 confidence\n"
"string target_type\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::autonomy_navigation::DangerCandidate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autonomy_navigation::DangerCandidate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.confidence);
      stream.next(m.target_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DangerCandidate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autonomy_navigation::DangerCandidate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autonomy_navigation::DangerCandidate_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTONOMY_NAVIGATION_MESSAGE_DANGERCANDIDATE_H
